### ISSUE TITLE
Identity is not created with dfx v0.14.1

### ISSUE THREAD

**Issue by bitdivine** [aviate-labs/setup-dfx#6]
## Expected Behavior
- An identity is created with the supplied key.

## Actual Behavior
- The job prints this many (maybe 1000) times:
```
Please enter a passphrase for your identity: 
```
- Then, when it exits, dfx is installed but not with the supplied key.

## Steps to Reproduce the Problem
- Set credentials in a GitHub workflow
```
      - name: Set credentials
        uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.14.1
          dfx-disable-encryption: true
        env:
          DFX_IDENTITY_PEM: ${{ secrets.DFX_IDENTITY_PEM }}
      - name: Verify identity
        run: |
          dfx identity whoami
          dfx identity get-principal          
```
- Observe the github action run.
  - This prints many times:
```
Please enter a passphrase for your identity: 
```
  - Then, verify identity prints  a principal that does not correspond to the key.

Note:  I have tried with and without `dfx-disable-encryption: true`

## Specifications

- Version(s): action version v0.2.3, dfx version 0.14.1
